using System;
using System.IO;
using System.Text;
using FFTColorCustomizer.GameBridge;
using Xunit;

namespace FFTColorCustomizer.Tests.GameBridge
{
    /// <summary>
    /// Iteration harness for reverse-engineering world_wldmes_bin.en.bin.
    /// These tests are marked Skip-if-file-missing so CI passes without the data file;
    /// when %TEMP%/world.bin exists, they dump decoded output to tmp/ for inspection.
    /// Once the decoder is stable, these become fact-based tests against known strings.
    /// </summary>
    public class WorldMesDecoderIterationTests
    {
        private static string? WorldBinPath()
        {
            var temp = Environment.GetEnvironmentVariable("TEMP");
            if (string.IsNullOrEmpty(temp)) return null;
            var path = Path.Combine(temp, "world.bin");
            return File.Exists(path) ? path : null;
        }

        private static string RepoTmpDir()
        {
            // Tests run from FFTColorCustomizer/bin/... — walk up to the repo root.
            var dir = AppContext.BaseDirectory;
            while (dir != null && !File.Exists(Path.Combine(dir, "FFTColorCustomizer.Tests.csproj")))
                dir = Path.GetDirectoryName(dir);
            if (dir == null) throw new DirectoryNotFoundException("Could not locate repo root");
            var tmp = Path.Combine(dir, "tmp");
            Directory.CreateDirectory(tmp);
            return tmp;
        }

        [Fact]
        public void DumpFullDecode()
        {
            var path = WorldBinPath();
            if (path == null) return; // skip when file not present

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);
            var decoded = WorldMesDecoder.Decode(bytes, 0, contentLen, markUnknown: true);

            var outPath = Path.Combine(RepoTmpDir(), "world_decode.txt");
            File.WriteAllText(outPath, decoded);
        }

        [Fact]
        public void DumpUnknownByteFrequency()
        {
            var path = WorldBinPath();
            if (path == null) return;

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);
            var counts = new int[256];
            for (int i = 0; i < contentLen; i++)
            {
                if (WorldMesDecoder.DecodeByte(bytes[i]) == null) counts[bytes[i]]++;
            }

            var sb = new StringBuilder();
            sb.AppendLine("byte\tcount");
            for (int b = 0; b < 256; b++)
            {
                if (counts[b] > 0) sb.AppendLine($"0x{b:x2}\t{counts[b]}");
            }
            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_unknown_bytes.txt"), sb.ToString());
        }

        /// <summary>
        /// Dump the raw byte sequence around every 0xF8 (paragraph separator candidate)
        /// so we can see what kind of transitions they bound. 8 bytes before, 8 after.
        /// </summary>
        [Fact]
        public void DumpParagraphSeparatorContexts()
        {
            var path = WorldBinPath();
            if (path == null) return;

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);
            var sb = new StringBuilder();

            int count = 0;
            for (int i = 0; i < contentLen && count < 50; i++)
            {
                if (bytes[i] == 0xF8)
                {
                    int s = Math.Max(0, i - 20);
                    int e = Math.Min(contentLen, i + 20);
                    var before = WorldMesDecoder.Decode(bytes, s, i - s, markUnknown: true);
                    var after = WorldMesDecoder.Decode(bytes, i + 1, e - i - 1, markUnknown: true);
                    sb.AppendLine($"[0x{i:x6}] ...{before} ||F8|| {after}...");
                    count++;
                }
            }
            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_f8_contexts.txt"), sb.ToString());
        }

        /// <summary>
        /// Emit a C# source file with the first N brave-story rumors as a static string
        /// array. Used to generate RumorCorpus.cs and then retire the 4MB binary.
        /// </summary>
        [Fact]
        public void EmitHardcodedRumorCorpus()
        {
            var path = WorldBinPath();
            if (path == null) return;
            var bytes = File.ReadAllBytes(path);
            var rumors = WorldMesDecoder.ExtractRumors(bytes);

            var take = System.Math.Min(26, rumors.Count);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by WorldMesDecoderIterationTests.EmitHardcodedRumorCorpus.");
            sb.AppendLine("// Source: world_wldmes_bin.en.bin brave-story pre-title region.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace FFTColorCustomizer.GameBridge");
            sb.AppendLine("{");
            sb.AppendLine("    public static class RumorCorpus");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly string[] Bodies = new string[]");
            sb.AppendLine("        {");
            for (int i = 0; i < take; i++)
            {
                var body = rumors[i].Body.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
                sb.AppendLine($"            \"{body}\",");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            File.WriteAllText(Path.Combine(RepoTmpDir(), "RumorCorpus.generated.cs"), sb.ToString());
        }

        [Fact]
        public void DumpExtractedRumorList()
        {
            var path = WorldBinPath();
            if (path == null) return;
            var bytes = File.ReadAllBytes(path);
            var rumors = WorldMesDecoder.ExtractRumors(bytes);
            var sb = new StringBuilder();
            sb.AppendLine($"Total rumors extracted: {rumors.Count}");
            foreach (var r in rumors)
            {
                var prev = r.Body.Length > 120 ? r.Body.Substring(0, 120) + "..." : r.Body;
                sb.AppendLine($"[{r.Index:D3}] @0x{r.Offset:X6} len={r.Body.Length}: {prev.Replace('\n', ' ')}");
            }
            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_rumor_list.txt"), sb.ToString());
        }

        /// <summary>
        /// Dump the pre-title region (before first E3 08) — this is where rumor bodies
        /// appear to live. Split on FE (hard-break) and print first 40 chars of each chunk.
        /// </summary>
        [Fact]
        public void DumpPreTitleRegion()
        {
            var path = WorldBinPath();
            if (path == null) return;

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);

            int firstTitle = -1;
            for (int i = 0; i + 1 < contentLen; i++)
            {
                if (bytes[i] == 0xE3 && bytes[i + 1] == 0x08) { firstTitle = i; break; }
            }
            if (firstTitle < 0) firstTitle = contentLen;

            // Split on FE and dump each chunk
            var sb = new StringBuilder();
            sb.AppendLine($"Pre-title region: 0 .. 0x{firstTitle:x6} ({firstTitle} bytes)");
            sb.AppendLine();

            int chunkStart = 0;
            int chunkIdx = 0;
            for (int i = 0; i <= firstTitle; i++)
            {
                if (i == firstTitle || bytes[i] == 0xFE)
                {
                    if (i > chunkStart)
                    {
                        var chunk = WorldMesDecoder.Decode(bytes, chunkStart, i - chunkStart, markUnknown: true);
                        var preview = chunk.Replace("\n", " ").Trim();
                        if (preview.Length > 200) preview = preview.Substring(0, 200);
                        sb.AppendLine($"[{chunkIdx:D4}] @0x{chunkStart:x6} len={i - chunkStart}: {preview}");
                        chunkIdx++;
                    }
                    chunkStart = i + 1;
                }
            }
            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_pretitle.txt"), sb.ToString());
        }

        /// <summary>
        /// Extract E3 08 ... E3 00 title brackets and the text that follows each up to the
        /// next E3 08 or end-of-content. Dumps (title, body-head-300-chars) pairs.
        /// </summary>
        [Fact]
        public void DumpTitleBlockRecords()
        {
            var path = WorldBinPath();
            if (path == null) return;

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);

            // Locate all E3 08 positions
            var titleStarts = new System.Collections.Generic.List<int>();
            for (int i = 0; i + 1 < contentLen; i++)
            {
                if (bytes[i] == 0xE3 && bytes[i + 1] == 0x08) titleStarts.Add(i);
            }

            var sb = new StringBuilder();
            sb.AppendLine($"Total E3 08 title markers: {titleStarts.Count}");
            sb.AppendLine();

            for (int r = 0; r < titleStarts.Count; r++)
            {
                int start = titleStarts[r];
                // Title runs from start+2 until next E3 (any follower)
                int titleEnd = start + 2;
                while (titleEnd < contentLen && bytes[titleEnd] != 0xE3) titleEnd++;

                int bodyStart = titleEnd;
                if (bodyStart + 1 < contentLen && bytes[bodyStart] == 0xE3) bodyStart += 2;

                int bodyEnd = (r + 1 < titleStarts.Count) ? titleStarts[r + 1] : contentLen;

                var title = WorldMesDecoder.Decode(bytes, start + 2, titleEnd - (start + 2), markUnknown: true);
                int bodyLen = System.Math.Min(bodyEnd - bodyStart, 300);
                var bodyHead = WorldMesDecoder.Decode(bytes, bodyStart, bodyLen, markUnknown: true);

                sb.AppendLine($"=== record #{r} @ 0x{start:x6} ===");
                sb.AppendLine($"title: {title}");
                sb.AppendLine($"body:  {bodyHead.Replace("\n", " | ")}");
                sb.AppendLine();
            }

            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_title_blocks.txt"), sb.ToString());
        }

        /// <summary>
        /// Once we identify record-separator candidates, dump the N highest-count bytes
        /// with their surrounding context, 4 examples each. Helps spot structural markers.
        /// </summary>
        [Fact]
        public void DumpHighFrequencyUnknownContexts()
        {
            var path = WorldBinPath();
            if (path == null) return;

            var bytes = File.ReadAllBytes(path);
            int contentLen = WorldMesDecoder.ContentLength(bytes);
            var counts = new int[256];
            for (int i = 0; i < contentLen; i++)
                if (WorldMesDecoder.DecodeByte(bytes[i]) == null) counts[bytes[i]]++;

            // Pick top 10 unknown bytes
            var topBytes = new System.Collections.Generic.List<(int b, int c)>();
            for (int b = 0; b < 256; b++)
                if (counts[b] > 0) topBytes.Add((b, counts[b]));
            topBytes.Sort((a, x) => x.c.CompareTo(a.c));

            var sb = new StringBuilder();
            foreach (var (b, c) in topBytes)
            {
                if (sb.ToString().Split('\n').Length > 200) break;
                sb.AppendLine($"=== byte 0x{b:x2} ({c} total) ===");
                int shown = 0;
                for (int i = 0; i < contentLen && shown < 5; i++)
                {
                    if (bytes[i] == (byte)b)
                    {
                        int s = Math.Max(0, i - 15);
                        int e = Math.Min(contentLen, i + 15);
                        var before = WorldMesDecoder.Decode(bytes, s, i - s, markUnknown: true);
                        var after = WorldMesDecoder.Decode(bytes, i + 1, e - i - 1, markUnknown: true);
                        sb.AppendLine($"  [0x{i:x6}] {before}||{b:x2}||{after}");
                        shown++;
                    }
                }
                sb.AppendLine();
            }
            File.WriteAllText(Path.Combine(RepoTmpDir(), "world_topbyte_contexts.txt"), sb.ToString());
        }
    }
}
